[[priority1]]
== Priority Area 1: Science and Research

*_Improving biodiversity evidence for scientific research and understanding_*

[[activity1-1]]
=== Activity 1.1: Drive mobilization and use of biodiversity data to support priority thematic areas of relevance

==== Projected outcomes for 2027

*	Knowledge gaps are reduced by consolidating data coverage across the thematic areas of relevance
*	GBIF’s relevance to research is enhanced, through increased recognition and uptake of GBIF mediated data among researchers across additional scientific disciplines

==== Indicative tasks for 2026

* Consolidate scientific expertise across the GBIF network—including researchers from national participants, thematic community experts, the Science Committee, and the GBIF Secretariat—to support development of strategic documents, communications, and improvements to GBIF-mediated data and services
* Expand GBIF’s relevance by engaging high-priority thematic communities of practice, including agrobiodiversity; support knowledge exchange, data flow, and community engagement; and advance thematic reporting, data discoverability, and identification of data gaps and biases
* Explore and map established and emerging data practices in global research; assess the usability and accessibility of GBIF infrastructure for researchers; and recommend improvements to tools and processes.
* Identify opportunities to integrate content from existing biodiversity data networks and repositories into GBIF, and demonstrate the benefits of increased visibility through the GBIF platform
* Ensure GBIF’s leadership by advocating for and participating in global initiatives that promote open science and open data

// *** *Expected funding mechanisms and sources*: Core funds: salaried staff, workshops and travel; Supplementary funds: Vector Atlas project.  

[[activity1-2]]
=== Activity 1.2: Advance GBIF’s capacity to mediate biodiversity survey and monitoring data and increase the spatiotemporal and taxonomic breadth of survey and monitoring data mediated by GBIF

==== Projected outcomes for 2027

* Reduce knowledge gaps by helping the network to set targets for consolidating data coverage across thematic, taxonomic, phylogenetic, spatial and temporal dimensions
* Enable, expand and diversify the uptake and application of GBIF-mediated data

==== Indicative tasks for 2026

* Demonstrate publishing of survey and monitoring data in Darwin Core Archive (DwC-A) format from all continents and realms; explore streamlining data pipelines to enhance interoperability with new and existing publishing institutions (e.g. eLTER, NEON, EDI)
* Support the implementation and further development of the proposed Darwin Core Data Package (DwC-DP) format by developing use cases across biodiversity domains that inform documentation and training resources and demonstrated examples of content publishing
* Inform infrastructure development that supports event-centric data in both DwC-A and DwC-DP formats, including data ingestion, discoverability, display and access
* Update existing and develop new training materials and use cases to support the publishing and access of survey and monitoring data through GBIF
* Showcase sampling-event data representation using both DwC-A and DwC-DP in GBIF; promote and support data mobilization through presentations and workshops at conferences and online platforms (e.g., Ecological Society of America, Society for Tropical Ecology, International Council for the Exploration of the Sea (ICES) Annual Science Conference)
* Run a data republication campaign to enhance existing occurrence datasets using the https://eco.tdwg.org/[Humboldt Extension for Ecological Inventories^]

// *** *Expected funding mechanisms and sources*: Core funds: salaried staff; Supplementary funds. 

[[activity1-3]]
=== Activity 1.3: Improve taxonomic balance and interoperability of biodiversity evidence in GBIF through DNA-derived nomenclatures, metabarcoding and eDNA data

==== Projected outcomes for 2027

* Knowledge gaps are reduced by consolidating data coverage across the thematic areas of relevance
* GBIF’s relevance to research is enhanced, through increased recognition and uptake of GBIF-mediated data among researchers across additional scientific disciplines

==== Indicative tasks for 2026

* Continue engagement targeting improvements in data coverage and quality from DNA-derived research and monitoring, including through expanded interoperability with partner infrastructures
* Lead the development and implementation of infrastructure for sequence-based occurrence search and improvement of filtering and download options for DNA-derived data
* Prototype functionalities required for ongoing taxonomic reinterpretation and standardization of DNA-derived data
* Explore the feasibility of managing and/or hosting a global catalogue of DNA reference libraries to enhance the interpretability and reuse of sequence-based biodiversity evidence
* Engage with major data providers and repositories of DNA sequences to scale up and improve data publishing pipelines and mobilize additional DNA-derived biodiversity data into GBIF

// *** *Expected funding mechanisms and sources*: Core funds: salaried staff, workshops and travel; Supplementary funds: EC grant; potential EC grant and GEF-8 funds.  

[[activity1-ongoing]]
=== Ongoing activities to support science and research

* Provide scientific advice and recommendations on feasibility and research relevance to support GBIF’s involvement in relevant projects under the Work Programme
* Maintain and update guides, training materials, and other resources aimed at research audiences
* Monitor the needs of data originators and users across the GBIF network, including survey and monitoring partners, DNA data infrastructures, the eDNA community, and international and national initiatives
* Capture and incorporate feedback from research communities to inform the ongoing development of the GBIF data model
* Support the development and maintenance of community standards for priority data areas—such as invasive and alien species, species interactions, survey and monitoring data, and DNA-derived data—through TDWG and other relevant standards bodies
* Communicate progress on DNA-derived data, survey and monitoring efforts, and other thematic areas to the GBIF network and partners
* Maintain the GBIF literature tracking programme to document and communicate the use of GBIF-mediated data in research
* Promote best practices for data citation using digital object identifiers (DOIs), including outreach to researchers and journal publishers
* Highlight and illustrate the use of GBIF-mediated data across scientific disciplines and thematic areas through GBIF.org and the annual Science Review
* Organize annual competitions such as the https://www.gbif.org/ebbe[Ebbe Nielsen Challenge^] and https://www.gbif.org/graduate-researchers-award[Graduate Researchers Awards^]
* Coordinate the collection of peer-reviewed articles and other publications describing key concepts and components of the GBIF network and infrastructure
* Increase the academic visibility of GBIF data and contributions—by individuals, organizations (including funders), and projects—through integration with infrastructures such as https://orcid.org/[ORCID^], https://ror.org/[Research Organization Registry^] (ROR) and https://www.crossref.org/services/funder-registry/[Open Funder Registry^] (OFR)
* Review and process submissions through the https://github.com/gbif/data-mobilization[Suggest a dataset tool^] to expand thematic data represented in GBIF
* Ensure GBIF representation—including Secretariat staff, node representatives, and regional contractors—at relevant scientific conferences, with appropriate materials, presentations, and training workshops
* Support integration of GBIF data and training into higher education curricula and the professional development of early-career biodiversity researchers

*** *Expected funding mechanisms and sources*: Core funds: salaried staff; Supplementary funds