[[priority2]]
== Priority Area 2: Policy and Partnerships

*_Developing partnerships that benefit policy and society_*

[[activity2-1]]
=== Activity 2.1: Expand and strengthen participation 

==== Projected outcomes for 2027

* GBIF national participation is expanded across currently under-represented regions, G20 economies and megadiverse countries
* Current Associate Participants have agreed pathways towards achieving or returning to voting participation
* GBIF is recognized as a key implementation partner for biodiversity-related projects supported by the https://www.thegef.org/[Global Environment Facility^] (GEF)

==== Indicative tasks for 2026

* Explore the use of regional meetings or other consultation formats to scope, strengthen and operationalize engagement with the UN https://www.cbd.int/[Convention on Biological Diversity^] (CBD) https://www.cbd.int/tsc/tscm/regionalcentres[regional and subregional support centres^] 
* Finalize guidance documents for Other Associate Participants (see <<§3.2,activity3-2>>)
* Review roles and functions of Other Associate Participants to clarify partnerships and strengthen participation, in consultation with the Executive Committee
* Develop and promote a clear value proposition for funders that aligns regional and thematic engagement with GBIF’s mission, and identify pipelines to channel funding into special purpose funds or targeted regional support mechanisms
* Develop and publish a practical guidance note for integrating GBIF tools and services into GEF https://www.thegef.org/publications/system-transparent-allocation-resources-star[System for Transparent Allocation of Resources^] (STAR) programming and national biodiversity finance strategies
* Coordinate with UN Environment Programme (UNEP) and UN Development Programme (UNDP) to ensure GBIF data services are reflected in at least one approved STAR proposal

// *** *Expected funding mechanisms and sources*: Core funds: salaried staff and travel.  

[[activity2-2]]
=== Activity 2.2: Support the science-policy interface 

==== Projected outcomes for 2027

* GBIF-mediated data is consistently and transparently applied and cited across multiple indicators used to monitor progress towards the goals and targets agreed through the CBD and integrated into national platforms and reporting processes 
* GBIF’s value in supporting the https://www.un.org/sustainabledevelopment[UN Sustainable Development Goals^] (SDGs) is recognized and reinforced through strategic partnerships with relevant international organizations focused on climate change, food security, human health and well-being, and both terrestrial and marine biodiversity such as the https://ipbes.net/[Intergovernmental Science-Policy Platform on Biodiversity and Ecosystem Services^] (IPBES)

==== Indicative tasks for 2026

* Renew memoranda of cooperation with at least three key international partners, such as  Group on Earth Observations Biodiversity Observation Network (GEO BON), UNEP, UN Food and Agriculture Organization (FAO), European Commission (EC)) to support shared policy objectives and increase visibility
* Strengthen GBIF’s contributions to CBD national reporting and https://www.cbd.int/gbf[Kunming-Montreal Global Biodiversity Framework^] (GBF) indicators through targeted collaboration with national focal points and indicator agencies
* Consolidate and promote policy use cases from across the network on other multilateral agreements, such as the https://www.ramsar.org/[Convention on Wetlands^] (Ramsar), the https://cites.org/eng[Convention on International Trade in Endangered Species of Wild Fauna and Flora^] (CITES), the https://www.cms.int/[Convention on the Conservation of Migratory Species of Wild Animals^] (CMS) and the https://www.unccd.int/[UN Convention to Combat Desertification^] (UNCCD), ensuring alignment with reporting frameworks and highlighting GBIF’s role in supporting implementation
* Develop data cube use cases through the EU-funded project, Biodiversity Building Blocks for Policy (B-Cubed) with a view to refining cube specifications to improve their uptake
* Promote the use of the Catalogue of Life (COL) taxonomic services supported by ChecklistBank in international fora and infrastructures

// *** *Expected funding mechanisms and sources*: Core funds: salaried staff and travel; Supplementary funds: EC grant.  

[[activity2-3]]
=== Activity 2.3: Support nature-positive outcomes from decisions in the business, financial and productive sectors

==== Projected outcomes for 2027

* Lending agreements prepared by private agencies, financial institutions and public development banks include clear and unequivocal requirements for sharing biodiversity data
*	Private companies, trade associations and consultancies in all global regions recognize GBIF as the preferred platform to share primary biodiversity data gathered through impact assessments and monitoring

==== Indicative tasks for 2026

* Increase targeted engagement with trade associations, certification schemes and environmental consultancies to introduce datasharing principles across their communities of practice
* Continue collaboration with the https://tnfd.global/[Taskforce on Nature-based Financial Disclosures^] (TNFD), including engaging as a data provider within the proposed Nature-related Data Public Facility (NDPU)
* Extend collaboration with Esri and build on support of integrated access to GBIF-mediated data within ArcGIS Desktop software

// *** *Expected funding mechanisms and sources*: Core funds: salaried staff and travel; Supplementary funds: potential Special Purpose Fund.  

[[activity2-ongoing]]
=== Ongoing activities to support policy and partnerships

* Attend CBD meetings, including COP 17 in Armenia, and contribute to consultations, working groups, subsidiary bodies in collaboration with GBIF delegations and nodes
* Continue engagement with IUCN to implement the Memorandum of Cooperation, including regular imports of checklist data from the https://www.iucnredlist.org/[IUCN Red List of Threatened Species^] and the https://griis.org/[Global Register of Introduced and Invasive Species^] (GRIIS)
* Manage Participation processes relating to Heads of Delegation, including administration and communication
* Maintain outreach to the G20 Research Innovation Working Group and related science-policy platforms as opportunities arise
* Support national and regional engagement with CBD focal points and subregional support centres to align technical collaboration and data use with GBIF capabilities
* Maintain ongoing partnership coordination with GEO BON, OBIS, and other global biodiversity data initiatives
* Continue to maintain and strengthen collaborations with key regional partners and contractors, including review and support for non-country participants
* Maintain bilateral engagement with multilateral environmental funds and agencies, including GEF, UNEP, and FAO, to align funding strategies and support proposals //
* Continue policy-level engagement and fundraising for One Health/Pandemic Prevention (Quadripartite: WOAH, FAO, WHO, UNEP)

*** *Expected funding mechanisms and sources*: Core funds: salaried staff; Supplementary funds. 
