[[priority3]]
== Priority Area 3: Community and Capacity

*_Developing the GBIF network to meet future needs and challenges_*

[[activity3-1]]
=== Activity 3.1: Communicating the value of GBIF

==== Projected outcomes for 2027

* The GBIF network, its audiences and its wider communities of practice are equipped with robust evidence that demonstrates its value and relevance to science, policy and society

==== Indicative tasks for 2026

* Steward GBIF’s brand identity and support its application and extension across the network 
* Publish a paper detailing GBIF’s governance, community, infrastructure and content that can serve as a general reference for citing GBIF as an infrastructure and describe GBIF after 25 years
* Create, design and implement framework for GBIF annual reports
* Coordinate a consistent and structured approach toward community engagement and communication with nodes, thematic communities and other communities of practice 
* Evaluate the operations and effectiveness of GBIF awards programmes
* Assess options to ensure the future sustainability and impact of the literature tracking programme
* Coordinate celebrations marking GBIF's 25th year of operations

// *** *Expected funding mechanisms and sources*: core funds: salaried staff, communication materials and travel.  

[[activity3-2]]
=== Activity 3.2: Support and strengthen GBIF nodes

==== Projected outcomes for 2027

* GBIF nodes provide a strong and stable foundation for data mobilization and use through the network
* The role of GBIF nodes as hubs for data mobilization and use is better understood and supported, especially at national level

==== Indicative tasks for 2026

* Work with the Nodes Steering Group (NSG) to evaluate how to enhance the impact of the Node Awards programme in advance of its next implementation in 2027 (see <<activity3-1,§3.1>>)
* Support the organization of six regional nodes meetings
* Explore the role of regional support teams in onboarding new node managers and re-onboarding inactive nodes
* Refine handbooks for regional representatives and regional support team members by providing complementary practical guidance
* Continue support for the task group on Indigenous data governance and build on its recommendations for guidance materials to enable the GBIF community to implement the https://datascience.codata.org/articles/10.5334/dsj-2020-043#the-care-principles-and-their-supporting-concepts[CARE Principles^]
* Incorporate training modules from the Global Nodes training into the node development curriculum and consult with nodes to plan new modules 
* Assess and refine (as needed) the updated capacity self-assessment tool for national nodes with the NSG
* Update guidance and course materials to clarify the roles of both national and organizational nodes (see also <<activity2-1,§2.1>>)
* Recruit the nodes community to pilot tools and processes for publishing and using https://gbif.github.io/dwc-dp/[Darwin Core Data Packages^] (DwC-DP)
* Organize a virtual course on joining GBIF as a formal Participant and establishing a Participant node

// ** *Expected funding mechanisms and sources*: Core funds: salaried staff, Global Nodes Meeting, Task Force expenses and travel; Supplementary funds:  potential GEF-8 funds, potential Special Purpose Fund (for Indigenous Data Governance task Group).  

[[activity3-3]]
=== Activity 3.3: Develop capacity and skills

==== Projected outcomes for 2027

* GBIF’s ongoing capacity support programmes are successfully concluded, and new support programmes are scoped
* Additional training and guidance resources are available to the community in multiple languages covering both data mobilization and data use

==== Indicative tasks for 2026

* Develop materials and support training activities around the DwC-DP
* Finalize the selection processes for the BID calls for proposals in and across target regions of Africa, the Pacific, and Latin America and the Caribbean (LAC)
* Launch BID-funded projects with regional kick-off webinars
* Work with regional support teams to deliver virtual and on-site training workshops to complement the work of the nodes and engage the broader community of practice 
* Coordinate the work and skills development of regional support teams to ensure they provide effective support of data mobilization and use
* Organize three BID regional capacity enhancement workshops for funded project teams using updated and translated materials
* Use a new reporting format developed for CESP grantees to monitor progress towards the goals in the capacity development framework
* Roll out capacity self-assessments and capacity indicators to monitor capacity and progress across all levels

// ** *Expected funding mechanisms and sources*: ore funds: salaried staff,  CESP grant funds and travel; Supplementary funds: EC BID grant; contributions from Norway and Finland to Priority Area 3 Special Purpose Fund; potential funding from the https://www.worldbank.org/en/programs/amazon-sustainable-landscapes-program[World Bank Amazon Sustainable Landscapes programme^].  

[[activity3-ongoing]]
=== Ongoing activities to support community and capacity

* Organize annual calls for projects under the Capacity Enhancement Support Programme (CESP)
* Support for new node managers through the node onboarding programme
* Support proposals to the hosted portal programme
* Support the Living Atlases community, including financial contribution to support a technical coordinator
* Provide support for digital documentation and related community consultation processes
* Operate effective communications that produce and disseminate news items and thematic content via GBIF.org, newsletters, social media and other relevant channels
* Maintain biennial cycle of nodes meetings with 2026 regional meetings and planning for global node activities at GB34
* Coordinate work of volunteers, including mentors, ambassadors, translators and reviewers
* Maintain and refine GBIF’s training curricula and support community reuse of these materials
* Provide regular technical support hours for nodes
* Support the GBIF Data Use club

*** *Expected funding mechanisms and sources*: Core funds: salaried staff; Supplementary funds.
