[[priority4]]
== Priority Area 4: Infrastructure and data products

*_Maintain and evolve infrastructure to advance biodiversity-related knowledge_*

[[activity4-1]]
=== Activity 4.1: Enhance robustness of the core GBIF infrastructure

==== Projected outcomes for 2027

* GBIF-maintained software and informatics infrastructure provides high, ongoing levels of availability and performance that keep pace with growth in data publication and use

==== Indicative tasks for 2026

NOTE: _Many previous tasks from §4.1 are now part of ongoing operations below_

* Complete the adoption of https://www.checklistbank.org/[ChecklistBank^]  as part of the core GBIF services for indexing checklist datasets, including updated public GBIF APIs and documentation, with particular consideration of regional requirements (continued from 2025)
* Optimize the GBIF.org search infrastructure (Elasticsearch) through schema revision and by exploring configurations for dedicated indexing nodes
* Expand the infrastructure to support download capabilities for the emerging Darwin Core Data Package format
* Develop data processing pipelines to support ingestion of Darwin Core Data Packages
* Improve automation of full data reprocessing to support monthly updates to the taxonomic backbone
* Evaluate current processes and the impact of efforts to stabilize occurrence identifiers; revise approaches if necessary

// ** *Expected funding mechanisms and sources*: Core funds: salaried staff, hardware procurement; Supplementary funds: EC grants; potential GEF-8 funds.  

[[activity4-2]]
=== Activity 4.2: Enhance support services for data publishers and users

==== Projected outcomes for 2027

* The expanding GBIF community of users are fully supported by a responsive help desk team and improved technical documentation
* The taxonomic and collections communities benefit from improvements in GBIF support to the https://www.gbif.org/grscicoll[Global Registry of Scientific Collections^] (GRSciColl) and the Catalogue of Life

==== Indicative tasks for 2026

NOTE: _Many previous tasks from §4.2 are now part of ongoing operations below_

* Mature processes around the ticketing system for managing help desk requests, including training and onboarding regional and thematic contractors (carried over)
* Develop documentation and guidance for contributing to and migrating to the Extended Release of the Catalogue of Life taxonomic backbone
* Revise the https://www.gbif.org/tools/data-validator[data validator tool^] to support Darwin Core Data Packages and eDNA-specific datasets; incorporate user feedback and consider additional data checks in the future, e.g. those related to Indigenous data governance
* Develop supporting guidance and tools for publishing using the Darwin Core Data Package
* Support the GRSciColl editor community through training events, explore the feasibility of tracking citations for collections and institutions and provide regular training to node managers
* Continue expanding technical documentation, focusing on publishing and services using Darwin Core Data Packages, GRSciColl, and the Registry
* Prepare and secure community input and review of updates to GBIF data user and data publisher agreements that comply with https://www.cbd.int/doc/decisions/cop-16/cop-16-dec-02-en.pdf[CBD COP Decision 16/2: Digital sequence information and genetic resources^], with guidance on CARE Principles and relevant Indigenous data governance frameworks as appropriate

// *** *Expected funding mechanisms and sources*: Core funds: salaried staff, contractors; Supplementary funds: Special Purpose Fund;  potential EC grant and GEF-8 funds.  

[[activity4-3]]
=== Activity 4.3: Enhance features and capabilities of the GBIF infrastructure

==== Projected outcomes for 2027

* Improved user interface to GBIF.org
* Improved capabilities for GBIF to handle ecological, collections, paleontological and phylogenetic data
* Data reuse increased through more stable GBIF identifiers

==== Indicative tasks for 2026

NOTE: _Many previous tasks from §4.3 are now part of ongoing operations below_

* Develop the https://mdt.gbif-test.org[Metabarcoding Data Toolkit^] (MDT) through the ongoing pilot https://www.gbif.org/metabarcoding[Metabarcoding Data Programme^]
** Improve usability based on community feedback
** Explore packaging options, such as support for local deployments
** Improve documentation and support pilot implementations
** Coordinate with communities working on metabarcoding data publication and standards
* Implement sequence-based occurrence search and improve filtering and download options for DNA-derived data
* Develop a prototype for continuous taxonomic interpretation of DNA-derived data using reference catalogues
* Expand capabilities to visualize, search, and download event-based survey and monitoring datasets
* Implement support for processing https://gbif.github.io/dwc-dp/[Darwin Core Data Package^] (DwC-DP) datasets and improve visualisations that showcase their richness
* Improve processing of occurrence records to annotate them using checklist content (e.g. `isMarine`, `isKnownInvasiveSpecies`)
* Explore options for adding additional GIS layers (e.g. elevation, land use) to GBIF.org and hosted portal deployments
* Add the ability to annotate species occurrence maps on GBIF to flag suspicious records
* Move the experimental “related records” functionality (clustering) into production APIs and services
* Explore options for marine and freshwater spatial filters and a vocabulary for water bodies, in support of the https://doi.org/10.35035/doc-e52v-5875[OBIS-GBIF 2024 Joint Action Plan for Marine Biodiversity Data^]
* Evaluate current processes related to occurrenceID stability and transition to more stable automation
* Continue implementing outcomes from the task group on Indigenous data governance, including adoption of Local Contexts labels at appropriate levels within the GBIF infrastructure
* Explore alternative sources to https://gadm.org[GADM.org^] for filtering records against global administrative boundaries

// *** *Expected funding mechanisms and sources*: Core funds: salaried staff; Supplementary funds: EC grant funding; potential EC grant and GEF-8 funds.

[[activity4-4]]
=== Activity 4.4: Drive data standards development

==== Projected outcomes for 2027

* The work to revise the data model used by GBIF is matured and applicable for use
* All controlled terms used in GBIF processing are managed in the vocabulary server

==== Indicative tasks for 2026

* Complete the DwC-DP ratification process in TDWG, and begin promotion, training, and support across the GBIF network (see <<activity3-3,§3.3>>)
* Conduct a systematic review of all documentation to reflect changes in standards, https://www.gbif.org[GBIF.org^], and new publishing tools
* Continue work on habitat-relevant terms (Realm, Biome) and associated controlled vocabularies within the Darwin Core Task Group
* Continue exploring use cases that require data modelling work, particularly those related to improved taxonomic checklist publishing and the targeted use of aggregate data from https://www.gbif.org[GBIF.org^]

//  *** *Expected funding mechanisms and sources*: Core funds: salaried staff; Supplementary funds: EC grant funding;  potential EC grant and GEF-8 funds.  

[[activity4-ongoing]]
=== Ongoing activities to support infrastructure and data products

The following GBIF products and services are supported through coordinated processes, including:

* *Requirements gathering* through GitHub issues, community webinars, Nodes events,  open forums and mailing lists
* *Continuous feature development* driven by user feedback and aligned with evolving data standards and best practices
* *Community support* via technical documentation, a responsive help desk, tutorials (e.g. data-blog.gbif.org), training, reviews of datasets and guides, and coordination of regional support teams, volunteers and translators
* *Software maintenance* to address technical debt, updating frameworks, and ensuring long-term robustness and security

==== Core Infrastructure and Tools

===== Integrated Publishing Toolkit (IPT)

* Widely installed data-publishing software used by GBIF Nodes and institutions
* Also offered as a fully managed, cloud-hosted service by the GBIF Secretariat, including updates, backups, and support

===== GBIF.org indexing platform and APIs

* Ingests, indexes, and processes data for quality control and enrichment using taxonomic and geospatial resources and controlled vocabularies
* Supports search, filtering, and download services, along with DOI-based citation tracking

===== ChecklistBank.org infrastructure

* Community repository for publishing and managing taxonomic checklists
* Includes editorial tools for projects like the Catalogue of Life, supporting the integration of source lists into unified taxonomies

===== https://registry.gbif.org[Registry^] and Directory services 

* Provides registration of institutions, datasets and access and authorisation services for users
* Indexes the dataset-level metadata and provides discovery services that enable external infrastructures to connect to GBIF
* Coordinates the endorsement processes that support the business needs of GBIF

===== Global Registry of Scientific Collections (GRSciColl)

* Centralized GBIF-hosted registry of community-maintained information on physical scientific collections
* Maintained by the GBIF Secretariat and edited by a global network of curators

===== Client libraries (rGBIF and pyGBIF)

* Official R and Python libraries for accessing and using GBIF-mediated data

===== Hosted portals

* Fully managed and hosted data portals offering curated access to subsets of GBIF data

===== Data snapshots and analytics

* https://www.gbif.org/occurrence-snapshots[Monthly snapshots^] of all GBIF data, delivered on Amazon AWS, Google BigQuery and Microsoft cloud infrastructure 
* Quarterly processing of all historical data snapshots to provide ongoing https://www.gbif.org/analytics/global[data summaries and country reports^]

===== Data citation and impact tracking

* Infrastructure for assigning DOIs for data downloads and ensuring consistent dataset citation
* Citation tracking systems identify and categorize usage, with ~6 peer-reviewed publications referencing GBIF data each day
* Annual GBIF Science Review highlights the impact of shared biodiversity data

===== Data centre operations (Copenhagen University)

* Capacity planning and procurement for physical hardware (3 racks)
* Server administration, including networking, monitoring, backup, and security
* Ongoing upgrades to operating systems and distributed computing framework

===== Manage technical partnerships

* Liaison and participation within open standards development processes; in particular with https://www.tdwg.org[Biodiversity Information Standards^] (TDWG) 
* Coordination, collaboration and integration of GBIF software, vocabularies and services with other projects; notably the Living Atlases community and OBIS
* Contribution to key Open Source Software libraries that GBIF relies upon 

// *** *Expected funding mechanisms and sources*: Core funds: salaried staff; Supplementary funds.
